### ISSUE TITLE
Design User Research Survey

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage-frontend#1]
Please make sure @jwaltrowski and I approve this :)

**Comment by Iamjacksplasmid** [comment]
Link to survey:
https://docs.google.com/forms/d/1E0b67HHaaUc0B6WptwteCoVGOKcsA3Fqqq2jdXf2fXE/edit

About 80% finished.  Needs questions for one more section.  Should be ready for distribution tomorrow.

**Comment by Iamjacksplasmid** [comment]
https://drive.google.com/open?id=1E0b67HHaaUc0B6WptwteCoVGOKcsA3Fqqq2jdXf2fXE

Survey is ready for review.

**Comment by Iamjacksplasmid** [comment]
@wonderwoman13 has looked it over and approved.  Moving on to survey distribution.
