### ISSUE TITLE
Deploy Ember App to Heroku

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage-frontend#10]
Will need to add the Ember buildpack

**Comment by veberle162** [comment]
@wonderwoman13 Do you want to have these both deployed from the same Heroku instance?  If so, you will need to give me access to our Heroku.

**Comment by wonderwoman13** [comment]
@veberle162 no - the way Heroku works, you push it up under your account and then add owners to it. Please push with your account and then add @danigirl329 and me to it. I'll Slack you the emails.

**Comment by wonderwoman13** [comment]
https://desolate-bastion-67272.herokuapp.com/
