### ISSUE TITLE
Send Out User Research Survey

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage-frontend#2]
Collect at least 50 responses

**Comment by Iamjacksplasmid** [comment]
Currently at about 90 submissions after pushing it to Code&Supply's mental health slack channel and Facebook's general news feed last night before I went to bed.  I've also submitted it to /r/ADHD, /r/medicalresearch, and /r/BipolarReddit.  There are approximately 21 more subreddits I want to mass-mail it to today, should be able to get most of them in one cross-post.  I'll take care of that at the meet-up tonight.
