### ISSUE TITLE
Implement Styleguide 

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage-frontend#22]
UX teams will hand over style guide. 

Fonts were supplied!

https://drive.google.com/drive/folders/0B-F-vmZViwz4QWpCSGJnZDdnaG8

**Comment by wonderwoman13** [comment]
@danigirl329 is this done?

**Comment by danigirl329** [comment]
This will be the last ticket to get closed because there are still design features that need completed.

**Comment by danigirl329** [comment]
Styleguide is implemented.
