### ISSUE TITLE
UX Question: How the User Know Where To Go On Their Phone?

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage-frontend#23]
I'm adding @danigirl329 as a collaborator on this one since she has a great eye for these challenges.

**Comment by Iamjacksplasmid** [comment]
Per conversation on Slack, we'll be going with an on-screen URL at the exhibit.  Several different options and styles were discussed, which will each be reflected in their own low-fidelity mockup to be reviewed and selected by the team this week.
