### ISSUE TITLE
Get Official Data for Resource (Illness) Blurb

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage-frontend#26]
Will ask Jason for this data, then will provide to @danigirl329 a spreadsheet.

**Comment by wonderwoman13** [comment]
@Iamjacksplasmid here is the link: 

https://drive.google.com/file/d/0BxBCISb5XAYzYl9wY1Z0Y0JOVk0/view?usp=drive_web

Please create a GDoc in our drive with the illness and its corresponding paragraph to seed the app.

**Comment by Iamjacksplasmid** [comment]
Here is the link to the GDoc:

https://drive.google.com/open?id=1nVKQuhlUlt5fe_wyBJRMxbk0e5gB_hHGCwgOrLgnoJc

And here's a link for Jason...it's the same DSM-V that he sent us, but it's got searchable text, and it can be highlighted and copied and stuff.  I thought he might like having it!

https://psicovalero.files.wordpress.com/2014/06/dsm-v-manual-diagnc3b3stico-y-estadc3adstico-de-los-trastornos-mentales.pdf
