### ISSUE TITLE
Low Res Mockups

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage-frontend#4]
- Initial screen with just the map and the form to submit illness
- Same screen where the form now prompts for an anecdote
- Same screen and the form prompts to opt in for more information
- Same screen and the form prompts for optin information
- Resource page of an illness where illness description is on top and anecdote is below

**Comment by wonderwoman13** [comment]
Mockups from client: https://drive.google.com/drive/folders/0BwwYexgzHKRvYVpteXYtYk11WlU

**Comment by Iamjacksplasmid** [comment]
Street View:  https://drive.google.com/open?id=0BzSjGWdjf4-aMEFDNUhzeWcza00

**Comment by Iamjacksplasmid** [comment]
Desktop Landing: https://drive.google.com/open?id=0BzSjGWdjf4-aeGd2SkhSMmdRMzA

**Comment by Iamjacksplasmid** [comment]
Desktop Form 1: https://drive.google.com/open?id=0BzSjGWdjf4-aSkRWbEFkZmEwTFE

**Comment by Iamjacksplasmid** [comment]
Desktom Form 2: https://drive.google.com/open?id=0BzSjGWdjf4-aV04xTWdDUVR4STA

**Comment by Iamjacksplasmid** [comment]
Desktop Form 3: https://drive.google.com/open?id=0BzSjGWdjf4-aS0JjSlFjVndHWVk
