### ISSUE TITLE
High Res Mockups

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage-frontend#6]
- Initial screen with just the map and the form to submit illness
- Same screen where the form now prompts for an anecdote
- Same screen and the form prompts to opt in for more information
- Same screen and the form prompts for optin information
- Resource page of an illness where illness description is on top and anecdote is below

Build from Low Res mockups and supply to the Frontend team

**Comment by wonderwoman13** [comment]
Fonts were supplied!

https://drive.google.com/drive/folders/0B-F-vmZViwz4QWpCSGJnZDdnaG8

**Comment by wonderwoman13** [comment]
Mockups from client: https://drive.google.com/drive/folders/0BwwYexgzHKRvYVpteXYtYk11WlU

**Comment by jwaltrowski** [comment]
Here's the projected Image. https://drive.google.com/open?id=0B77jfrlLDg2jbW9BYkhRLW1fYUU

**Comment by jwaltrowski** [comment]
Web Landing!
https://drive.google.com/open?id=0B77jfrlLDg2jbW9BYkhRLW1fYUU

**Comment by jwaltrowski** [comment]
https://drive.google.com/open?id=0B77jfrlLDg2jbW9BYkhRLW1fYUU This is the medical condition write up and story page.  I hurried this up so @danigirl329 can get cracking on it.

**Comment by wonderwoman13** [comment]
I'm going to close for now since this fulfills the mockups needed for the presentation. I highly encourage @jwaltrowski revisiting this if Frontend needs it or when he is building out his portfolio.
