### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage-frontend#7]
Follow Bloc's setup on Style Guides
Both UX Designers need to agree on this
Provide to Frontend when complete

**Comment by wonderwoman13** [comment]
Fonts were supplied!

https://drive.google.com/drive/folders/0B-F-vmZViwz4QWpCSGJnZDdnaG8

**Comment by jwaltrowski** [comment]
https://drive.google.com/open?id=0B77jfrlLDg2jYzJBLWVoczlHOXc
