### ISSUE TITLE
Demo Day Presentation

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage-frontend#8]
With Britt's help, create an outline of the presentation then build it out. It needs to be something we can easily flip through on a tablet as the judges pass through.

**Comment by wonderwoman13** [comment]
@jwaltrowski and I were looking at Adobe products and I really like the idea of using Adobe Spark for the presentation. We can load it on a tablet and let the judge walk through it as we talk. Thoughts? @Iamjacksplasmid

**Comment by Iamjacksplasmid** [comment]
Took a look at Spark and yeah, I really liked the "Web Stories" demo video on the site.  I think we could put that to great use...it's flashier and more stylish than powerpoint or google slides, and it allows Jeff and I to put another software package in our portfolios, so I'm 100% down with it.

**Comment by jwaltrowski** [comment]
The presentation https://spark.adobe.com/page/JIofUpRFnhTgY/

**Comment by jwaltrowski** [comment]
https://spark.adobe.com/page/JIofUpRFnhTgY/
Updated to remove typo

**Comment by jwaltrowski** [comment]
https://spark.adobe.com/page/JIofUpRFnhTgY/ Added the line about Tags in future, fixed Britt's typos.

**Comment by wonderwoman13** [comment]
Sent to Jason! 👍
